SET MODE Oracle;

CREATE SCHEMA IF NOT EXISTS LAB_BAC;

CREATE TABLE IF NOT EXISTS LAB_BAC.PEOPLE
(	ID NUMBER(20,0) NOT NULL ENABLE,
    UUID VARCHAR2(64) NOT NULL,
    FIRST_NAME VARCHAR2(512),
    LAST_NAME VARCHAR2(512),
    TITLE VARCHAR2(512),
    MIN_ROLE VARCHAR(32),
    CREATION_DATE TIMESTAMP
);

COMMENT ON TABLE LAB_BAC.PEOPLE IS 'Elenco di persone';
COMMENT ON COLUMN LAB_BAC.PEOPLE.id IS 'Identificativo della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.UUID IS 'ID esterno della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.FIRST_NAME IS 'Nome della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.LAST_NAME IS 'Cognome della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.TITLE IS 'Titolo della persona';
COMMENT ON COLUMN LAB_BAC.PEOPLE.CREATION_DATE IS 'Data di creazione della persona';

CREATE SEQUENCE IF NOT EXISTS LAB_BAC.SEQ_PEOPLE START WITH 10000 INCREMENT BY 1 MAXVALUE 99999999999 CACHE 1;

INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, '46005e2d-4faa-4c5a-8ed2-6876d63622a7', 'Margherita', 'Hack', 'Astrofisica', null, SYSDATE );
INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, '62472b90-14a5-45b5-891e-14f9e5659680', 'Alan', 'Turing', 'Matematico', null, SYSDATE );
INSERT INTO LAB_BAC.PEOPLE VALUES ( LAB_BAC.SEQ_PEOPLE.nextval, '3ad86124-765a-4104-a2dd-e99335ff1260', 'Richard', 'Feynman', 'Fisico', 'admin', SYSDATE );

-- Scenario 1: dati personali (ownership) - visibili solo all'owner o a un admin
CREATE TABLE IF NOT EXISTS LAB_BAC.PERSONAL_NOTE
(   ID NUMBER(20,0) NOT NULL ENABLE,
    UUID VARCHAR2(64) NOT NULL,
    OWNER_UPN VARCHAR2(128) NOT NULL,
    TITLE VARCHAR2(512),
    CONTENT VARCHAR2(4000),
    CREATION_DATE TIMESTAMP
);
CREATE SEQUENCE IF NOT EXISTS LAB_BAC.SEQ_PERSONAL_NOTE START WITH 20000 INCREMENT BY 1 MAXVALUE 99999999999 CACHE 1;

-- Scenario 3: documenti txt di ufficio (multi-tenant + gerarchia ruoli)
CREATE TABLE IF NOT EXISTS LAB_BAC.OFFICE_DOCUMENT
(   ID NUMBER(20,0) NOT NULL ENABLE,
    UUID VARCHAR2(64) NOT NULL,
    OWNER_UPN VARCHAR2(128) NOT NULL,
    OWNER_OFFICE VARCHAR2(128) NOT NULL,
    OWNER_ROLE VARCHAR2(32),
    STATUS VARCHAR2(16),
    FILE_NAME VARCHAR2(512),
    CONTENT VARCHAR2(4000),
    CREATION_DATE TIMESTAMP
);
CREATE SEQUENCE IF NOT EXISTS LAB_BAC.SEQ_OFFICE_DOCUMENT START WITH 30000 INCREMENT BY 1 MAXVALUE 99999999999 CACHE 1;

-- Destinatari di condivisione esplicita (sharing) per OFFICE_DOCUMENT (@ElementCollection)
CREATE TABLE IF NOT EXISTS LAB_BAC.OFFICE_DOCUMENT_SHARED_WITH
(   OFFICE_DOCUMENT_ID NUMBER(20,0) NOT NULL ENABLE,
    SHARED_UPN VARCHAR2(128) NOT NULL
);

-- Dati demo per gli scenari a grana fine (solo per esplorazione interattiva; i test NON dipendono da questi dati).
-- Identità demo (claim office del JWT): EINSTEIN/FISICA, BOHR/FISICA(admin), PLANCK/FISICA(guest), FERMI/FISICA,
-- MENDELEEV/CHIMICA(admin), LAVOISIER/CHIMICA.
INSERT INTO LAB_BAC.PERSONAL_NOTE VALUES ( LAB_BAC.SEQ_PERSONAL_NOTE.nextval, 'a1a1a1a1-0000-0000-0000-000000000001', 'EINSTEIN', 'Appunti privati', 'Nota personale di Einstein (visibile solo a lui o a un admin)', SYSDATE );

INSERT INTO LAB_BAC.OFFICE_DOCUMENT VALUES ( LAB_BAC.SEQ_OFFICE_DOCUMENT.nextval, 'b1b1b1b1-0000-0000-0000-000000000001', 'EINSTEIN', 'FISICA', 'user', 'PUBLISHED', 'relativita.txt', 'Documento pubblicato di Einstein (FISICA, ruolo soglia user)', SYSDATE );
INSERT INTO LAB_BAC.OFFICE_DOCUMENT VALUES ( LAB_BAC.SEQ_OFFICE_DOCUMENT.nextval, 'b1b1b1b1-0000-0000-0000-000000000002', 'BOHR', 'FISICA', 'admin', 'PUBLISHED', 'meccanica-quantistica.txt', 'Documento di Bohr (FISICA, soglia admin: solo admin dello stesso ufficio)', SYSDATE );
INSERT INTO LAB_BAC.OFFICE_DOCUMENT VALUES ( LAB_BAC.SEQ_OFFICE_DOCUMENT.nextval, 'b1b1b1b1-0000-0000-0000-000000000003', 'MENDELEEV', 'CHIMICA', 'admin', 'DRAFT', 'tavola-periodica.txt', 'Bozza di Mendeleev (CHIMICA): visibile solo all owner finche non pubblicata', SYSDATE );

-- Appuntamenti: visibilita multi-parte (creatore / scienziato / admin ufficio) + regola temporale sul delete
CREATE TABLE IF NOT EXISTS LAB_BAC.APPOINTMENT
(   ID NUMBER(20,0) NOT NULL ENABLE,
    UUID VARCHAR2(64) NOT NULL,
    CREATOR_UPN VARCHAR2(128) NOT NULL,
    SCIENTIST_UPN VARCHAR2(128) NOT NULL,
    OFFICE VARCHAR2(128) NOT NULL,
    APPOINTMENT_AT TIMESTAMP,
    SUBJECT VARCHAR2(512),
    CREATION_DATE TIMESTAMP
);
CREATE SEQUENCE IF NOT EXISTS LAB_BAC.SEQ_APPOINTMENT START WITH 40000 INCREMENT BY 1 MAXVALUE 99999999999 CACHE 1;

-- Appuntamento demo (data lontana, sempre > 24h): creato da EINSTEIN con BOHR, ufficio FISICA.
-- Visibile a EINSTEIN (creatore), BOHR (scienziato e admin FISICA); NON a Mendeleev (CHIMICA).
INSERT INTO LAB_BAC.APPOINTMENT VALUES ( LAB_BAC.SEQ_APPOINTMENT.nextval, 'c1c1c1c1-0000-0000-0000-000000000001', 'EINSTEIN', 'BOHR', 'FISICA', TIMESTAMP '2030-01-15 10:30:00', 'Discussione sui quanti', SYSDATE );
